# Generated by Django 3.2.11 on 2022-01-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.FloatField(default=0.0, verbose_name='price')),
                ('description', models.TextField(default='no_description', max_length=255, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Product',
                'managed': True,
            },
        ),
    ]
